projetSymfony/src/Entity/Contient.php
<?php

namespace App\Entity;

use App\Repository\ContientRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ContientRepository::class)]
class Contient
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $quantite = null;

    #[ORM\Column]
    private ?bool $Acheter = null;

    #[ORM\ManyToOne(inversedBy: 'Contenue')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Liste $Dans = null;

    #[ORM\ManyToOne(inversedBy: 'contients')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Article $Contenue = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getQuantite(): ?int
    {
        return $this->quantite;
    }

    public function setQuantite(int $quantite): static
    {
        $this->quantite = $quantite;

        return $this;
    }

    public function isAcheter(): ?bool
    {
        return $this->Acheter;
    }

    public function setAcheter(bool $Acheter): static
    {
        $this->Acheter = $Acheter;

        return $this;
    }

    public function getDans(): ?Liste
    {
        return $this->Dans;
    }

    public function setDans(?Liste $Dans): static
    {
        $this->Dans = $Dans;

        return $this;
    }

    public function getContenue(): ?Article
    {
        return $this->Contenue;
    }

    public function setContenue(?Article $Contenue): static
    {
        $this->Contenue = $Contenue;

        return $this;
    }
}

projetSymfony/src/Entity/Liste.php
<?php

namespace App\Entity;

use App\Repository\ListeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ListeRepository::class)]
class Liste
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;


    #[ORM\Column(length: 255)]
    private ?string $Nom_Liste = null;

    #[ORM\ManyToOne(inversedBy: 'Listes')]
    private ?User $Id_user = null;

    #[ORM\OneToMany(targetEntity: Contient::class, mappedBy: 'Dans')]
    private Collection $Contenue;

    public function __construct()
    {
        $this->Contenue = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomListe(): ?string
    {
        return $this->Nom_Liste;
    }

    public function setNomListe(string $Nom_Liste): static
    {
        $this->Nom_Liste = $Nom_Liste;

        return $this;
    }

    public function getIdUser(): ?User
    {
        return $this->Id_user;
    }

    public function setIdUser(?User $Id_user): static
    {
        $this->Id_user = $Id_user;

        return $this;
    }

    /**
     * @return Collection<int, Contient>
     */
    public function getContenue(): Collection
    {
        return $this->Contenue;
    }

    public function addContenue(Contient $contenue): static
    {
        if (!$this->Contenue->contains($contenue)) {
            $this->Contenue->add($contenue);
            $contenue->setDans($this);
        }

        return $this;
    }

    public function removeContenue(Contient $contenue): static
    {
        if ($this->Contenue->removeElement($contenue)) {
            // set the owning side to null (unless already changed)
            if ($contenue->getDans() === $this) {
                $contenue->setDans(null);
            }
        }

        return $this;
    }
}

projetSymfony/src/Form/ListeType.php
<?php

namespace App\Form;

use App\Entity\Liste;
use App\Entity\User;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ListeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            
            ->add('Nom_Liste')
            
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Liste::class,
        ]);
    }
}

projetSymfony/src/Controller/ListeController.php
<?php

namespace App\Controller;

use App\Entity\Liste;
use App\Form\ListeType;
use App\Repository\ListeRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use App\Entity\Contient;
use App\Repository\ContientRepository;
use App\Repository\UserRepository;

#[Route('/liste')]
class ListeController extends AbstractController
{
    #[Route('/', name: 'app_liste_index', methods: ['GET'])]
    public function index(Request $request, ListeRepository $listeRepository, ContientRepository $contientRepository, UserRepository $userRepository): Response
    {
        $liste = new Liste();
        $user = $this->getUser();
        $liste->setIdUser($user);
        $form = $this->createForm(ListeType::class, $liste);
        $form->handleRequest($request);
        
        $listes = $listeRepository->findAll();
            
        $user = $this->getUser();
        $listes = array_filter($listes, function($liste) use ($user) {
            return $liste->getIdUser() == $user;
        });

        $prix_max = $contientRepository->findMaxPriceByUser($user);
        $total = $contientRepository->sumPriceByUser($user);
        $min = $contientRepository->findMinPriceByUser($user);
        $avg = $contientRepository->findByAvgPriceByUser($user);
        $dept = $contientRepository->findByTypeDepense($user);

        return $this->render('liste/index.html.twig',[
            'listes' => $listeRepository->findAll(),
            'form' => $form,
            'prix_max' => $prix_max,
            'total' => $total,
            'prix_min' => $min,
            'avg' => $avg,
            'expensesByType' => $dept,
        ]);
        
    }
    
    #[Route('/', name: 'app_liste_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $liste = new Liste();
        $user = $this->getUser();
        $liste->setIdUser($user);
        $form = $this->createForm(ListeType::class, $liste);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($liste);
            $entityManager->flush();

            return $this->redirectToRoute('app_liste_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('liste/new.html.twig', [
            'liste' => $liste,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_liste_show', methods: ['GET'])]
    public function show(Liste $liste): Response
    {
        return $this->render('liste/show.html.twig', [
            'liste' => $liste,
        ]);
    }
    
    // #[Route('/{id}', name: 'app_liste_show', methods: ['GET'])]
    // public function show(Liste $liste, ContientRepository $contientRepository): Response
    // {
    //     $articles = $contientRepository->findBy(['Dans' => $liste]);

    //     return $this->render('liste/show.html.twig', [
    //         'liste' => $liste,
    //         'articles' => $articles,
    //     ]);
    // }

    #[Route('/{id}/edit', name: 'app_liste_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Liste $liste, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ListeType::class, $liste);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_liste_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('liste/edit.html.twig', [
            'liste' => $liste,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_liste_delete', methods: ['POST'])]
    public function delete(Request $request, Liste $liste, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$liste->getId(), $request->request->get('_token'))) {
            $entityManager->remove($liste);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_liste_index', [], Response::HTTP_SEE_OTHER);
    }



    // Ajoutez cette méthode pour traiter l'ajout à la liste
    #[Route('/add_to_list', name: 'app_add_to_list', methods: ['POST'])]
    public function addToCart(Request $request, EntityManagerInterface $entityManager): Response
    {
        // Récupérez les données envoyées par la requête AJAX
        $data = json_decode($request->getContent(), true);
    
        // Récupérez l'objet Liste correspondant à l'ID envoyé depuis la requête AJAX
        $liste = $this->getDoctrine()->getRepository(Liste::class)->find($data['listeId']);
    
        // Vérifiez si la liste existe
        if (!$liste) {
            return new Response('Liste not found', Response::HTTP_NOT_FOUND);
        }
    
        // Parcourez les articles sélectionnés et ajoutez-les à la liste dans la table "contient"
        foreach ($data['articleIds'] as $articleId) {
            $article = $this->getDoctrine()->getRepository(Article::class)->find($articleId);
       
            $existingContient = $this->getDoctrine()->getRepository(Contient::class)->findOneBy(['Dans' => $liste, 'Contenue' => $article]);
    


            if ($existingContient) {
                // Si l'article existe déjà, augmentez simplement la quantité
                $existingContient->setQuantity($existingContient->getQuantity() + $data['quantity']);
            } else {
                // Sinon, créez une nouvelle entrée dans la table "contient" avec la quantité spécifiée
                $contient = new Contient();
                $contient->setListe($liste);
                $contient->setArticle($article);
                $contient->setQuantity($data['quantity']);
        
                // Persistez l'entité contient
                $entityManager->persist($contient);
            }
        }
    
        // Flush pour enregistrer les changements dans la base de données
        $entityManager->flush();
    
        // Répondez à la requête AJAX avec un message de succès ou une redirection
        return new Response('Articles added to list successfully', Response::HTTP_OK);
    }
    

    // Ajoutez cette méthode pour traiter la suppression de la liste
    #[Route('/remove_from_list/{listeId}', name: 'app_remove_from_list', methods: ['POST'])]
    public function removelist(Request $request, EntityManagerInterface $entityManager, ListeRepository $listeRepository): Response
    {
        // Supprimez la liste de la base de données
        $liste = $listeRepository->find($request->get('listeId'));
        //Delete tout les contient de la liste
        $contient = $entityManager->getRepository(Contient::class)->findBy(['Dans' => $liste]);
        foreach ($contient as $contient) {
            $entityManager->remove($contient);
        }
        $entityManager->remove($liste);
        $entityManager->flush();
        return new Response('List has been deleted', Response::HTTP_OK);
    }

    
}

projetSymfony/templates/liste/_delete_form.html.twig
<form method="post" action="{{ path('app_liste_delete', {'id': liste.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ liste.id) }}">
    <button class="btn">Delete</button>
</form>

projetSymfony/templates/liste/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

projetSymfony/templates/liste/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Liste{% endblock %}

{% block body %}
<h1 id="modifNomList">Modifier la liste</h1>
<div class="containerEditList">
   

    {{ include('liste/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_liste_index') }}">back to list</a>
</div>

{% endblock %}

projetSymfony/templates/liste/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste index{% endblock %}

{% block body %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js"></script>

<header>
    <a>Listes</a>
    <a href="{{ path('app_article_index') }}">Produits</a>
</header>

<div class="new">
    <h1>Créer une nouvelle liste</h1>
    {{ form_start(form) }}
        {{ form_widget(form) }}
        <button class="btn">{{ button_label|default('Save') }}</button>
    {{ form_end(form) }}
</div>

<div class="statistique-container">
    <div class="statistique-left">
        <h1>Statistique générale</h1>

        <p>Le prix le plus élevé : {{ prix_max }}</p>
        <p>Le prix le plus bas : {{ prix_min }}</p>
        <p>Le prix moyen : {{ avg }}</p>
        <p>Somme dépensée : {{ total }}</p>
        <p>Depense par type de produit : </p>
        
            {% for expense in expensesByType %}
                <p>{{ expense.Type }} : {{ expense.total }} €</p>
            {% endfor %}
     </ul>
    </div>
    <div class="statistique-right">
        <canvas id="myChart" style="width:100%;max-width:400px"></canvas>
    </div>
</div>

<script>
const xType = [];
const yPrice = [];
const barColors = ["red", "green", "blue", "orange", "brown"];
{% for expense in expensesByType %}
    xType.push("{{ expense.Type }}");
    yPrice.push("{{ expense.total }}");
{% endfor %}

new Chart("myChart", {
    type: "doughnut",
    data: {
        labels: xType,
        datasets: [{
            backgroundColor: barColors,
            data: yPrice
        }]
    },
    options: {
        title: {
            display: true,
            text: "Dépense par type de produit"
        }
    }
});
</script>

<div class="courses">
    <h1>Vos listes de courses !</h1>
    {% set counter = 1 %}
    {% for liste in app.user.getListes() %}
        <div class="liste-courses">
            <table>
                <tr>
                    <td>{{ counter }}</td>
                    <td>{{ liste.getNomListe() }}</td>
                    <td>
                        <a href="{{ path('app_liste_show', {'id': liste.id}) }}">Voir</a>
                        <a href="{{ path('app_liste_edit', {'id': liste.id}) }}">Modifier</a>
                        <a href="#" onclick="event.preventDefault(); if (confirm('Are you sure?')) { document.getElementById('remove-list-form-{{ liste.id }}').submit(); }">Supprimer</a>
                        <form id="remove-list-form-{{ liste.id }}" action="{{ path('app_remove_from_list', {'listeId': liste.id}) }}" method="post" style="display: none;">
                            <input type="hidden" name="_method" value="POST">
                            <input type="hidden" name="_token" value="{{ csrf_token('remove-list' ~ liste.id) }}">
                        </form>
                    </td>
                </tr>
            </table>
            {% set counter = counter + 1 %}
        </div>
    {% endfor %}
</div>

{% endblock %}

projetSymfony/templates/liste/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Liste{% endblock %}

{% block body %}
    <h1>Create new Liste</h1>

    {{ include('liste/_form.html.twig') }}

    <a href="{{ path('app_liste_index') }}">back to list</a>
{% endblock %}

projetSymfony/templates/liste/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Articles de la liste {{ liste.NomListe }}{% endblock %}


{% block body %}
<header>
  <a>Listes</a>
  <a href="{{ path('app_article_index') }}">Produits</a>
</header>


 <div class = "contenue">
 {% set total = 0 %}
    {% for contenue in liste.Contenue %}
      {% set total = total + contenue.Contenue.prix * contenue.quantite %}
    {% endfor %}
    <h1>Articles de la liste {{ liste.NomListe }} Total: {{total}}€</h1>
   <hr class="horizontal-bar">

      
        <div class = "cards">
            {% for contenue in liste.Contenue %}
            
            <div class ="container">
              <img src="{{ asset('images/' ~ contenue.Contenue.NomProduit ~ '.png') }}" alt={{contenue.Contenue.NomProduit}}>
                <form method="post" action="{{ path('app_contient_delete_article', {'id': contenue.id}) }}">
                        <button type="submit" class="supprimer">
                            <img src="{{ asset('images/Poubelle.png') }}" alt="poubelle">
                        </button>
                     </form>
                
                <div class = "detail">
            
                  <p class = "price">{{ contenue.Contenue.NomProduit }}</p>
                   <h2>{{ contenue.Contenue.prix }}€</h2>
                 </div>
                 <div class ="quantite">
                    
                    <form method="post" action="{{ path('app_contient_decrease_quantity', {'id': contenue.id}) }}">
                        <button type="submit" class="moins">-</button>
                    </form>

                    <h3>Quantité : {{ contenue.quantite }}</h3>

                    <form method="post" action="{{ path('app_contient_increase_quantity', {'id': contenue.id}) }}">
                         <button type="submit" class="plus">+</button>
                    </form>
                </div>

                <div class="buy">
                    <form method="post" action="{{ path('app_contient_buy', {'id': contenue.id}) }}">
                       
                        {% if contenue.acheter %}
                            <button type="submit" class="acheter-true">Acheter</button>
                        {% else %}
                            <button type="submit" class="acheter-false">Acheter</button>
                        {% endif %}
                        
                    </form>
                </div>

                  
            </div>
            {% endfor %}
            </div>
            
                       
        
 </div>
    <a href="{{ path('app_liste_index') }}">Retour aux listes</a>
   
{% endblock %}